flows:
  companies_house:
    run_id: 978
  glass:
    run_id: 414
  google_search:
    params:
      anchor_periods:
        jan2019_onward: 2019-01-01 2021-01-25
      term_salience_threshold: 0.1
      test_mode: false
    run_id: 1005
  nspl:
    run_id: 633
  glass_house:
    params:
      test_mode: false
    run_id: 920
  nomis:
    params:
      test_mode: false
      years:
      - 2018
    run_id: 386
fetch_urls:
  sic_taxonomy: https://www.ons.gov.uk/file?uri=/methodology/classificationsandstandards/ukstandardindustrialclassificationofeconomicactivities/uksic2007/sic2007summaryofstructurtcm6.xls
descriptive:
  nuts1: 'Scotland'
  months: ["2020-04-01","2020-09-01","2021-01-01"]
  lads: ["Highland", "Aberdeen City", "Stirling"]
diversification:
  nuts1: 'Scotland'
  months: ["2020-04-01","2020-09-01","2021-01-01"]
  lads: ['East Lothian','Aberdeenshire','Stirling']
modelling:
  nuts1: 'Scotland'
